on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        lfs: true

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        cache: pip
        cache-dependency-path: |
          requirements.txt
          setup.py

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install setuptools wheel build ninja cmake
        pip install -r requirements.txt

    - name: Build and test
      shell: cmd
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64
        cmake --build build --config Release
        python -m pytest tests/ --cov=dx11_renderer --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Build wheel
      shell: cmd
      run: |
        python -m build --wheel
        if errorlevel 1 (
          echo "Wheel build failed"
          if exist log\wheel_build_log.txt type log\wheel_build_log.txt
          exit /b 1
        )

    - name: Store package
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/*.whl
        retention-days: 7